config:
  chronicle_funds: 10.
  timechain_url: 'wss://archive.integration.analog.one'
  prices_path: 'prices.csv'
  testers_path: 'testers.csv'
backends:
  evm:
    chain_dict: "auxiliary/chains.json"
    factory: "auxiliary/factory.json"
    proxy: "contracts/GatewayProxy.sol/GatewayProxy.json"
    gateway: "contracts/Gateway.sol/Gateway.json"
    tester: "contracts/GmpProxy.sol/GmpProxy.json"
    zenswap: "contracts/ZenSwap.sol/ZenSwap.json"
    zenswap_plugin: "contracts/ZenSwapGmpPlugin.sol/ZenSwapGmpPlugin.json"
networks:
  10:
    backend: "evm"
    name: "ethereum sepolia"
    url: "wss://ethereum-sepolia-rpc.publicnode.com"
    gateway_funds: 1.
    chronicle_funds: .1
    batch_size: 16
    batch_offset: 0
    batch_gas_limit: 18000000
    gmp_margin: 0.0
    shard_task_limit: 100
    route_gas_limit: 10000000
    route_base_fee: 1400000000
    shard_size: 6
    shard_threshold: 4
    coin_id: 1027
    cctp_contracts:
    - "F804E7B9bf2a1644c490c87Fdb18642ef329601C"
    - "D2b0db0D3E48DeA780Fa6C417B015A0950D2A4A9"
    cctp_url: "https://iris-api-sandbox.circle.com/attestations/"
    zenswap: 
      universal_router: "4A7b5Da61326A6379179b40d00F57E5bbDC962c2"
      permit2: "000000000022D473030F116dDEE9F6B43aC78BA3"
      token_messenger: "aCF1ceeF35caAc005e15888dDb8A3515C41B4872"
      msg_transmitter: "7865fAfC2db2093669d92c0F33AeEF291086BEFD"
      usdc: "0x1c7D4B196Cb0C7B01d743Fbc6116a902379C7238"

  11:
    backend: "evm"
    name: "astar shibuya"
    url: "wss://rpc.shibuya.astar.network"
    gateway_funds: 10.
    chronicle_funds: 10.
    batch_size: 32
    batch_offset: 0
    batch_gas_limit: 30000000
    gmp_margin: 0.0
    shard_task_limit: 100
    route_gas_limit: 10000000
    route_base_fee: 1400000000
    shard_size: 6
    shard_threshold: 4
    coin_id: 12885
  12:
    backend: "evm"
    name: "binance testnet"
    url: "wss://bsc-testnet-rpc.publicnode.com"
    gateway_funds: 1.
    chronicle_funds: .5
    batch_size: 128
    batch_offset: 0
    batch_gas_limit: 50000000
    gmp_margin: 0.0
    shard_task_limit: 100
    route_gas_limit: 10000000
    route_base_fee: 1400000000
    shard_size: 6
    shard_threshold: 4
    coin_id: 1839
  13:
    backend: "evm"
    name: "arbitrum sepolia"
    url: "wss://arbitrum-sepolia-rpc.publicnode.com"
    gateway_funds: 1.
    chronicle_funds: .5
    batch_size: 1024
    batch_offset: 0
    batch_gas_limit: 500000000000000
    gmp_margin: 0.0
    shard_task_limit: 100
    route_gas_limit: 10000000
    route_base_fee: 1400000000
    shard_size: 6
    shard_threshold: 4
    coin_id: 11841
    cctp_contracts:
    - "293B37788019317F09d015b56895F0CB6Fc53Fa7"
    cctp_url: "https://iris-api-sandbox.circle.com/attestations/"
chronicles: 
- https://chronicle-1.integration.analog.one
- https://chronicle-2.integration.analog.one
- https://chronicle-3.integration.analog.one
- https://chronicle-4.integration.analog.one
- https://chronicle-5.integration.analog.one
- https://chronicle-6.integration.analog.one
- https://chronicle-7.integration.analog.one
- https://chronicle-8.integration.analog.one
- https://chronicle-9.integration.analog.one
- https://chronicle-10.integration.analog.one
- https://chronicle-11.integration.analog.one
- https://chronicle-12.integration.analog.one
- https://chronicle-13.integration.analog.one
- https://chronicle-14.integration.analog.one
- https://chronicle-15.integration.analog.one
- https://chronicle-16.integration.analog.one
- https://chronicle-17.integration.analog.one
- https://chronicle-18.integration.analog.one
- https://chronicle-19.integration.analog.one
- https://chronicle-20.integration.analog.one
- https://chronicle-21.integration.analog.one
- https://chronicle-22.integration.analog.one
- https://chronicle-23.integration.analog.one
- https://chronicle-24.integration.analog.one
